name: mineral
description: Mineral is a Discord framework for designing discord bots in Dart.
version: 1.2.0

repository: https://github.com/mineral-dart/core
# homepage: https://www.example.com

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.1
  path: ^1.8.2
  http: ^0.13.4
  interact: ^2.1.1
  collection: ^1.16.0
  mineral_ioc: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  mineral: mineral

